import { LabValue } from '@/lib/types';

interface ExportData {
  values: LabValue[];
  questions?: any[];
  timestamp: string;
}

export function generateSimpleExport(data: ExportData): string {
  const { values, questions, timestamp } = data;
  
  let content = '';
  
  // Header
  content += '═══════════════════════════════════════════════════════\n';
  content += '           LAB RESULTS LITERACY COMPANION\n';
  content += '              Doctor Visit Preparation\n';
  content += '═══════════════════════════════════════════════════════\n\n';
  
  content += `Generated: ${new Date(timestamp).toLocaleString()}\n\n`;
  
  content += '⚠️  IMPORTANT: This is an educational tool only.\n';
  content += '    Not medical advice. Discuss with your healthcare provider.\n\n';
  
  // Results Summary
  content += '═══════════════════════════════════════════════════════\n';
  content += 'LAB RESULTS SUMMARY\n';
  content += '═══════════════════════════════════════════════════════\n\n';
  
  // Count abnormal values
  const abnormalValues = values.filter(v => v.status !== 'normal');
  const lowValues = values.filter(v => v.status === 'low');
  const highValues = values.filter(v => v.status === 'high');
  
  content += `Total Markers: ${values.length}\n`;
  content += `Normal: ${values.length - abnormalValues.length}\n`;
  content += `Abnormal: ${abnormalValues.length} (${lowValues.length} low, ${highValues.length} high)\n\n`;
  
  // Detailed Results
  content += '───────────────────────────────────────────────────────\n';
  content += 'DETAILED RESULTS\n';
  content += '───────────────────────────────────────────────────────\n\n';
  
  values.forEach((value, idx) => {
    const statusSymbol = value.status === 'low' ? '↓' : 
                        value.status === 'high' ? '↑' : '●';
    const statusLabel = value.status.toUpperCase();
    
    content += `${idx + 1}. ${value.marker}\n`;
    content += `   Value: ${value.value} ${value.unit}\n`;
    content += `   Reference Range: ${value.referenceRange}\n`;
    content += `   Status: ${statusSymbol} ${statusLabel}\n`;
    if (value.confidence < 0.9) {
      content += `   Note: Confidence ${Math.round(value.confidence * 100)}% - please verify with doctor\n`;
    }
    content += '\n';
  });
  
  // Questions Section
  if (questions && questions.length > 0) {
    content += '═══════════════════════════════════════════════════════\n';
    content += 'QUESTIONS FOR YOUR DOCTOR\n';
    content += '═══════════════════════════════════════════════════════\n\n';
    
    questions.forEach((q, idx) => {
      content += `${q.marker}:\n`;
      q.questions.forEach((question: string, qIdx: number) => {
        content += `   ${qIdx + 1}. ${question}\n`;
      });
      content += '\n';
    });
  }
  
  // Space for Notes
  content += '═══════════════════════════════════════════════════════\n';
  content += 'NOTES FROM DOCTOR VISIT\n';
  content += '═══════════════════════════════════════════════════════\n\n';
  content += '\n\n\n\n\n\n\n\n';
  
  // Footer
  content += '───────────────────────────────────────────────────────\n';
  content += 'Generated by Lab Results Literacy Companion\n';
  content += 'Privacy-first • Educational only • Not medical advice\n';
  content += '───────────────────────────────────────────────────────\n';
  
  return content;
}

export function downloadTextFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}