export interface ExportOptions {
  includeLearning: boolean;
  includeQuestions: boolean;
  abnormalOnly: boolean;
}

export function generateSimpleExport(
  markerName: string,
  context: {
    whatIsIt: string;
    whyMeasured: string[];
    researchContext: string;
  },
  questions: string[],
  options: ExportOptions
): string {
  const date = new Date().toLocaleDateString();
  let content = '';

  // Header
  content += '═══════════════════════════════════════════════════════\n';
  content += '           MY LEARNING SUMMARY\n';
  content += `              ${markerName}\n`;
  content += `              ${date}\n`;
  content += '═══════════════════════════════════════════════════════\n\n';

  // Learning Summary
  if (options.includeLearning) {
    content += 'WHAT I LEARNED\n';
    content += '─────────────────────────────────────────────────────\n\n';
    content += `What is ${markerName}?\n`;
    content += `${context.whatIsIt}\n\n`;
    content += 'Why is it measured?\n';
    context.whyMeasured.forEach((reason) => {
      content += `• ${reason}\n`;
    });
    content += '\n';
    content += 'What research says:\n';
    content += `${context.researchContext}\n\n`;
    content += 'My notes:\n';
    content += '________________________________________________________________\n\n';
    content += '________________________________________________________________\n\n';
    content += '________________________________________________________________\n\n\n';
  }

  // Questions
  if (options.includeQuestions) {
    content += 'QUESTIONS FOR MY DOCTOR\n';
    content += '─────────────────────────────────────────────────────\n\n';
    questions.forEach((question) => {
      content += `□ ${question}\n`;
    });
    content += '\nAdditional questions:\n';
    content += '□ ________________________________________________________\n\n';
    content += '□ ________________________________________________________\n\n\n';
  }

  // Doctor's Notes
  content += 'NOTES FROM DOCTOR VISIT\n';
  content += '─────────────────────────────────────────────────────\n\n';
  content += 'Date: _______________\n\n';
  content += "Doctor's explanation:\n";
  content += '________________________________________________________________\n\n';
  content += '________________________________________________________________\n\n';
  content += '________________________________________________________________\n\n\n';
  content += 'Next steps:\n';
  content += '□ ________________________________________________________\n\n';
  content += '□ ________________________________________________________\n\n';
  content += '□ ________________________________________________________\n\n\n';
  content += 'Follow-up appointment: _______________\n\n\n';

  // Footer
  content += '═══════════════════════════════════════════════════════\n';
  content += 'Generated by Lab Results Literacy Companion\n';
  content += 'Educational only • Not medical advice\n';
  content += '═══════════════════════════════════════════════════════\n';

  return content;
}

export function downloadTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}