// lib/agents/context/loader.ts
import medgemmaData from '@/data/medgemma-outputs.json';
import { MarkerContext } from '../types';

type MedGemmaMarkers = Record<
  string,
  {
    explanation: string;
    research_context: string;
    food_patterns: string;
    raw_output: string;
  }
>;

/**
 * Global disclaimer added to all context objects for safety, transparency, and legal defensibility
 */
const GLOBAL_DISCLAIMER =
  'This is educational information only, generated by MedGemma 1.5 4B using population-level data. ' +
  'It is NOT medical advice, diagnosis, treatment, or personalized nutrition guidance. ' +
  'Always consult your healthcare provider or registered dietitian for interpretation of your lab results ' +
  'and any dietary or health decisions.';

/**
 * Get MedGemma-generated context for a specific marker, with fallback
 * ✅ IMPORTANT: Never throws — returns fallback MarkerContext when missing.
 */
export function getMedGemmaContent(markerName: string): MarkerContext {
  // Normalize marker name (handles common lab abbreviations and variations)
  const normalizedName = normalizeMarkerName(markerName);

  const markers = medgemmaData.markers as MedGemmaMarkers;

  // Try exact match first (fastest)
  let content = markers[normalizedName];

  // Try variations if exact match fails
  if (!content) {
    const variations = [
      normalizedName,
      markerName, // Original
      normalizedName.replace(/[\(\)]/g, '').trim(), // Without parentheses
      markerName.replace(/[\(\)]/g, '').trim(),
    ];

    for (const variant of variations) {
      // Try exact match
      if (markers[variant]) {
        content = markers[variant];
        break;
      }

      // Try case-insensitive match
      const lowerVariant = variant.toLowerCase();
      const matchingKey = Object.keys(markers).find(
        (key) => key.toLowerCase() === lowerVariant
      );
      if (matchingKey) {
        content = markers[matchingKey];
        break;
      }
    }
  }

  // ✅ Non-fatal fallback (no throw)
  if (!content) {
    console.warn(
      `No MedGemma content for: "${markerName}" (normalized: "${normalizedName}")`
    );

    return {
      markerName: normalizedName,
      whatIsIt: `${markerName} is a common lab marker used by healthcare providers to assess various aspects of health.`,
      researchContext:
        'Research discusses population-level patterns related to this marker. Individual results vary.',
      foodPatterns:
        'A balanced diet supports overall health. Discuss personalized guidance with your clinician.',
      generatedBy: 'Fallback',
      generatedAt: new Date().toISOString(),
      disclaimer: GLOBAL_DISCLAIMER,
    };
  }

  return {
    markerName: normalizedName,
    whatIsIt: content.explanation,
    researchContext: content.research_context,
    foodPatterns: content.food_patterns,
    generatedBy: 'MedGemma 1.5 4B',
    generatedAt: medgemmaData.generated_at,
    disclaimer: GLOBAL_DISCLAIMER,
  };
}

/**
 * Get list of all supported marker names
 */
export function getAllMarkers(): string[] {
  return Object.keys(medgemmaData.markers);
}

/**
 * Check if content exists for a given marker (case-insensitive)
 */
export function hasMarkerContent(markerName: string): boolean {
  const normalized = normalizeMarkerName(markerName).toLowerCase();
  return Object.keys(medgemmaData.markers).some(
    (key) => key.toLowerCase() === normalized
  );
}

/**
 * Normalize common lab abbreviations and formatting variations
 */
function normalizeMarkerName(name: string): string {
  const lower = name.toLowerCase().trim();

  const normalizations: Record<string, string> = {
    hgb: 'Hemoglobin',
    hb: 'Hemoglobin',
    hemoglobin: 'Hemoglobin',
    hba1c: 'Hemoglobin A1C',
    a1c: 'Hemoglobin A1C',
    'hemoglobin a1c': 'Hemoglobin A1C',

    // LDL variants (fixes the "(calc)" cases)
    ldl: 'LDL Cholesterol',
    'ldl cholesterol': 'LDL Cholesterol',
    'ldl cholesterol (calc)': 'LDL Cholesterol',
    'ldl (calc)': 'LDL Cholesterol',

    hdl: 'HDL Cholesterol',
    'hdl cholesterol': 'HDL Cholesterol',
    chol: 'Total Cholesterol',
    cholesterol: 'Total Cholesterol',
    'total cholesterol': 'Total Cholesterol',
    tsh: 'TSH (thyroid stimulating hormone)',
    alt: 'ALT (alanine aminotransferase)',
    ast: 'AST (aspartate aminotransferase)',
    alp: 'Alkaline Phosphatase',
    'alkaline phosphatase': 'Alkaline Phosphatase',
    egfr: 'eGFR (kidney function)',
    bun: 'Blood Urea Nitrogen (BUN)',
    'blood urea nitrogen': 'Blood Urea Nitrogen (BUN)',
    wbc: 'White Blood Cells (WBC)',
    'white blood cells': 'White Blood Cells (WBC)',
    rbc: 'Red Blood Cells (RBC)',
    'red blood cells': 'Red Blood Cells (RBC)',
    plt: 'Platelets',
    platelets: 'Platelets',
    mcv: 'Mean Corpuscular Volume (MCV)',
    'mean corpuscular volume': 'Mean Corpuscular Volume (MCV)',
    mch: 'Hemoglobin', // MCH is related to hemoglobin
    mchc: 'Hemoglobin', // MCHC is also related to hemoglobin
    rdw: 'Red Blood Cells (RBC)', // RDW is related to RBC
    hct: 'Hematocrit',
    hematocrit: 'Hematocrit',
    glucose: 'Glucose (fasting)',
    'vit d': 'Vitamin D',
    'vitamin d': 'Vitamin D',
    b12: 'Vitamin B12',
    'vitamin b12': 'Vitamin B12',
    folate: 'Folate',
    ferritin: 'Ferritin (iron storage)',
    iron: 'Iron',
    creatinine: 'Creatinine',
    sodium: 'Sodium',
    potassium: 'Potassium',
    calcium: 'Calcium',
    chloride: 'Chloride',
    triglycerides: 'Triglycerides',
    bilirubin: 'Bilirubin',
    t4: 'T4 (thyroxine)',
  };

  if (normalizations[lower]) {
    return normalizations[lower];
  }

  // If not in map, return as-is with proper capitalization
  // DON'T remove parentheses - they might be needed!
  return name
    .split(/[\s-]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
    .trim();
}

/**
 * Get context for a marker, with optional value for future value-specific enhancements
 * ✅ Since getMedGemmaContent() never throws anymore, this will not crash runs.
 */
export async function generateContextForMarker(
  markerName: string,
  value?: number
): Promise<MarkerContext> {
  const context = getMedGemmaContent(markerName);

  // Optional: Future value-specific enhancement (e.g., flag if outside typical range)
  if (value !== undefined) {
    // Example placeholder – expand later with reference ranges per marker
    // context.valueNote = `Your measured value: ${value} (reference ranges vary by lab and demographics)`;
  }

  return context;
}
