// lib/agents/context/loader.ts
import medgemmaData from '@/data/medgemma-outputs.json';
import { MarkerContext } from '../types';

type MedGemmaMarkers = Record<string, {
  explanation: string;
  research_context: string;
  food_patterns: string;
  raw_output: string;
}>;

/**
 * Global disclaimer added to all context objects for safety, transparency, and legal defensibility
 */
const GLOBAL_DISCLAIMER =
  "This is educational information only, generated by MedGemma 1.5 4B using population-level data. " +
  "It is NOT medical advice, diagnosis, treatment, or personalized nutrition guidance. " +
  "Always consult your healthcare provider or registered dietitian for interpretation of your lab results " +
  "and any dietary or health decisions.";

/**
 * Get MedGemma-generated context for a specific marker, with fallback
 */
export function getMedGemmaContent(markerName: string): MarkerContext {
  // Normalize marker name (handles common lab abbreviations and variations)
  const normalizedName = normalizeMarkerName(markerName);

  // Try exact match first (fastest)
  let content = (medgemmaData.markers as MedGemmaMarkers)[normalizedName];

  // Fallback: case-insensitive search across all keys
  if (!content) {
    const lowerNormalized = normalizedName.toLowerCase();
    const matchingKey = Object.keys(medgemmaData.markers).find(
      key => key.toLowerCase() === lowerNormalized
    );
    if (matchingKey) {
      content = (medgemmaData.markers as MedGemmaMarkers)[matchingKey];
    }
  }

  if (!content) {
    throw new Error(
      `No MedGemma content found for marker: "${markerName}" (normalized: "${normalizedName}")`
    );
  }

  return {
    markerName: normalizedName,
    whatIsIt: content.explanation,
    researchContext: content.research_context,
    foodPatterns: content.food_patterns,
    generatedBy: 'MedGemma 1.5 4B',
    generatedAt: medgemmaData.generated_at,
    disclaimer: GLOBAL_DISCLAIMER,
  };
}

/**
 * Get list of all supported marker names
 */
export function getAllMarkers(): string[] {
  return Object.keys(medgemmaData.markers);
}

/**
 * Check if content exists for a given marker (case-insensitive)
 */
export function hasMarkerContent(markerName: string): boolean {
  const normalized = normalizeMarkerName(markerName).toLowerCase();
  return Object.keys(medgemmaData.markers).some(
    key => key.toLowerCase() === normalized
  );
}

/**
 * Normalize common lab abbreviations and formatting variations
 */
function normalizeMarkerName(name: string): string {
  const lower = name.toLowerCase().trim();

  const normalizations: Record<string, string> = {
    'hgb': 'Hemoglobin',
    'hb': 'Hemoglobin',
    'hba1c': 'Hemoglobin A1C',
    'a1c': 'Hemoglobin A1C',
    'ldl': 'LDL Cholesterol',
    'hdl': 'HDL Cholesterol',
    'chol': 'Total Cholesterol',
    'tsh': 'TSH (thyroid stimulating hormone)',
    'alt': 'ALT (alanine aminotransferase)',
    'ast': 'AST (aspartate aminotransferase)',
    'alp': 'Alkaline Phosphatase',
    'egfr': 'eGFR (kidney function)',
    'bun': 'Blood Urea Nitrogen (BUN)',
    'wbc': 'White Blood Cells (WBC)',
    'rbc': 'Red Blood Cells (RBC)',
    'plt': 'Platelets',
    'mcv': 'Mean Corpuscular Volume (MCV)',
    'vit d': 'Vitamin D',
    'vitamin d': 'Vitamin D',
    'b12': 'Vitamin B12',
    'folate': 'Folate',
    'ferritin': 'Ferritin (iron storage)',
    'iron': 'Iron',
    // Add more as you expand
  };

  if (normalizations[lower]) {
    return normalizations[lower];
  }

  // Clean formatting: capitalize words, remove extra spaces/parentheses if needed
  return name
    .replace(/[\(\)]/g, '') // remove parentheses
    .split(/[\s-]+/)       // split on spaces or hyphens
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
    .trim();
}

/**
 * Get context for a marker, with optional value for future value-specific enhancements
 */
export async function generateContextForMarker(
  markerName: string,
  value?: number
): Promise<MarkerContext> {
  try {
    const context = getMedGemmaContent(markerName);

    // Optional: Future value-specific enhancement (e.g., flag if outside typical range)
    if (value !== undefined) {
      // Example placeholder – expand later with reference ranges per marker
      // context.valueNote = `Your measured value: ${value} (reference ranges vary by lab and demographics)`;
    }

    return context;

  } catch (error) {
    console.error(`Error loading context for marker "${markerName}":`, error);

    // Safe fallback to prevent app breakage
    return {
      markerName,
      whatIsIt: `${markerName} is a common lab marker used by healthcare providers to assess various aspects of health.`,
      researchContext: 'Research discusses population-level patterns related to this marker. Individual results vary.',
      foodPatterns: 'A balanced diet following USDA guidelines supports overall health. Discuss with your doctor.',
      generatedBy: 'Fallback',
      generatedAt: new Date().toISOString(),
      disclaimer: GLOBAL_DISCLAIMER,
    };
  }
}